/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fcf9f3',
        'surface-dim': '#dcdad4',
        'surface-bright': '#fcf9f3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f3ed',
        'surface-container': '#f0eee8',
        'surface-container-high': '#ebe8e2',
        'surface-container-highest': '#e5e2dc',
        'on-surface': '#1c1c18',
        'on-surface-variant': '#53433d',
        'inverse-surface': '#31312d',
        'inverse-on-surface': '#f3f0ea',
        'outline': '#86736c',
        'outline-variant': '#d9c2ba',
        'primary': '#8c4a2f',
        'on-primary': '#ffffff',
        'primary-container': '#a96245',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#ffb599',
        'secondary': '#396759',
        'on-secondary': '#ffffff',
        'secondary-container': '#b9ead9',
        'on-secondary-container': '#3d6b5e',
        'tertiary': '#7a5500',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#996c04',
        'on-tertiary-container': '#fffbff',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#ffdbce',
        'primary-fixed-dim': '#ffb599',
        'on-primary-fixed': '#370e00',
        'on-primary-fixed-variant': '#71361c',
        'secondary-fixed': '#bceddc',
        'secondary-fixed-dim': '#a0d1c0',
        'on-secondary-fixed': '#002019',
        'on-secondary-fixed-variant': '#204f42',
        'tertiary-fixed': '#ffdeaa',
        'tertiary-fixed-dim': '#f5bd58',
        'on-tertiary-fixed': '#271900',
        'on-tertiary-fixed-variant': '#5f4100',
        'background': '#fcf9f3',
        'on-background': '#1c1c18',
        'surface-variant': '#e5e2dc',
      },
      fontFamily: {
        'display': ['Noto Serif SC', 'serif'],
        'body': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-hero-mobile': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0.01em' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0.01em' }],
        'label-sm': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      spacing: {
        'section-gap-desktop': '120px',
        'section-gap-mobile': '64px',
        'gutter': '24px',
        'container-max-width': '1280px',
      },
      borderRadius: {
        'sm': '0.25rem',
        'DEFAULT': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
